baseURL = "https://lorenzifrancesco.github.io"
languageCode = "en-us"
title = "Francesco Lorenzi"
theme = "papermod"

# Enable this for better debugging
# disableKinds = ["taxonomy", "taxonomyTerm"]

# PaperMod specific settings
[params]
  author = "Francesco Lorenzi"
  defaultTheme = "light" # default theme (dark, light, auto)
  disableThemeToggle =  true
  showReadingTime = true # show estimated reading time
  hideMeta = true
  showPostNavLinks = true # show next/prev post navigation links
  useHugoToc = false # use Hugo's built-in Table of Contents
  math = true
  ShowCodeCopyButtons = true
  ShowBreadCrumbs = true
  ShowToc=false
  social =true
  mainSections = []
  
[params.assets]
  css = ["css/extended/custom.css"]
  favicon = "fava.png"
  favicon16x16 = "fava.png"
  favicon32x32 = "fava.png"

[markup]
  [markup.highlight]
    # style = "monokai"
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  tag = "tags"

[permalinks]
  tags = "/tags/:slug/"

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 1
  [[menus.main]]
    name = 'Bio'
    pageRef = '/bio.md'
    weight = 2
  [[menus.main]]
    name = 'Research'
    pageRef = '/research.md'
    weight = 3
  [[menus.main]]
    name = 'Talks and seminars'
    pageRef = '/talks.md'
    weight = 4
  [[menus.main]]
    name = 'Scientific posts'
    pageRef = '/posts.md'
    weight = 5

[outputs]
home = ["HTML", "RSS", "JSON"]  # necessary for search
